version: '3'

services:
  db:
    container_name: shift_database
    image: mysql/mysql-server:8.0
    command: --init-file /data/application/init.sql
    volumes:
        - ./backend/database/mysql.init.sql:/data/application/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: verysecuredpassword
      MYSQL_DATABASE: perspective
      MYSQL_USER: shift
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql-docker
    ports:
      - "8081:8080"
  backend:
    build: ./backend
    ports: 
      - "8090:8090"
  frontend:
    build: ./frontend
    ports: 
      - "8080:3000"
      