version: '3'

services:
  db:
    image: mysql/mysql-server:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: verysecuredpassword
      MYSQL_DATABASE: perspective
    ports:
      - "3306:3306"
  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql-docker
    ports:
      - "8081:8080"
  backend:
    build: ./backend
    ports: 
      - "8090:8090"
  frontend:
    build: ./frontend
    ports: 
      - "8080:8080"
      